### ISSUE TITLE
暂停下载后重新下载失败

### ISSUE THREAD

**Issue by Travellingpoet** [ssseasonnn/DownloadX#16]
暂停下载后再开启下载 进度到百分之99就下载不动 返回failure 可能还剩几百个字节下载失败

**Comment by ssseasonnn** [comment]
提供一下日志，或者下载链接，你光说个下载失败我也不知道啥原因呀

**Comment by Travellingpoet** [comment]
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at com.north.arrow.module.common.download.core.RangeDownloader$download$3$deferred$1.invokeSuspend(RangeDownloader.kt:131)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
好像是缓冲区的问题

**Comment by ssseasonnn** [comment]
下载链接发一下呢

**Comment by Travellingpoet** [comment]
下载链接是公司内网的 但是浏览器可以正常下载

**Comment by Travellingpoet** [comment]
我使用你的demo也偶尔会出现这种情况 下载停止之后继续下载返回onfailure

**Comment by ssseasonnn** [comment]
好的

**Comment by Travellingpoet** [comment]
`response.body()?.use {
                it.byteStream().use { source ->
                    val tmpFileBuffer = tmpFile.mappedByteBuffer(startByte(), RANGE_SIZE)
                    val shadowFileBuffer = shadowFile.mappedByteBuffer(current, remainSize())

                    val buffer = ByteArray(8192)
                    var readLen = source.read(buffer)

                    while (isActive && readLen != -1) {
                        L.d("DownLoadBuffer source:${source.read()}")
                        L.d("DownLoadBuffer readLine:$readLen")
                        L.d("DownLoadBuffer remain:${end - current}")
                        shadowFileBuffer.put(buffer, 0, readLen)


                        current += readLen

                        tmpFileBuffer.putLong(16, current)

                        sendChannel.send(readLen)

                        readLen = source.read(buffer)
                    }
                }
            }`
看了一下这段源码 我暂停后重新读取流的时候最后一次读取的长度比remainSize还要大

DownLoadBuffer source:53
DownLoadBuffer readLine:8191
DownLoadBuffer remain:1178
是不是RangeDownLoader下载流的问题？
